name: Release Beta

on:
  push:
    tags:
      - "beta/**"

jobs:
  build_android:
    name: Build Android beta
    type: build
    params:
      platform: android
      profile: beta

  build_ios:
    name: Build iOS beta
    type: build
    params:
      platform: ios
      profile: beta

  submit_android:
    name: Submit Android to open testing
    needs: [build_android]
    type: submit
    params:
      build_id: ${{ needs.build_android.outputs.build_id }}
      profile: beta

  testflight:
    name: Distribute iOS to TestFlight
    needs: [build_ios]
    type: testflight
    params:
      build_id: ${{ needs.build_ios.outputs.build_id }}
      profile: beta
      external_groups: ["External Testers"]
      changelog: ${{ github.commit_message || 'Beta release' }}
