name: Distribute Beta to TestFlight

on:
  app_store_connect:
    build_upload:
      states:
        - complete

jobs:
  testflight:
    name: Distribute iOS to TestFlight
    type: testflight
    params:
      asc_build_id: ${{ app_store_connect.build_upload.build.id }}
      external_groups: ["External Testers"]
      changelog: Beta release
